### ISSUE TITLE
Uri parsing doesn't support multipart parameters

### ISSUE THREAD

**Issue by fommil** [Spinoco/protocol#16] opened 2017-11-30 09:14 UTC
```
scala> val x = "http://x.com/123?a=1&b=2;c=3"
x: String = http://x.com/123?a=1&b=2;c=3

scala> Uri.parse(x)
res0: scodec.Attempt[spinoco.protocol.http.Uri] = Failure(1: Cannot decode query parameter into key-value pair: List(b, 2;c, 3))
```

The above is compliant according to

- https://tools.ietf.org/html/rfc7230#page-82
- https://tools.ietf.org/html/rfc3986
- https://tools.ietf.org/html/rfc6570

and I've definitely seen URLs like this a lot over my career

```
?a=1&b=foo;bar;baz;gaz=daz&c=lolz
```

(not saying I endorse using them... but we have to work with what we're given...)

In both cases the correct parsing of the values is `2;c=3` and `foo;bar;baz;gaz=daz` respectively, with userland expected to deal with further parsing of the semicolons. I've also seen URL encoded `&` used as the separator at this layer.

Would it be hard to support this? Where should we start looking?

It seems the inverse works, i.e. constructing a `Uri` with these expected values and then `.stringify`ing them.

**Comment by fommil** [comment] 2017-12-04 09:32
Likewise, when re-creating a String from a Url, any values containing `;` will have them url-encoded rather than left raw. How can I disable url encoding of `;` in query values?

**Comment by pchlupacek** [comment] 2017-12-04 09:45
@fommil the issue is in codec of Uri, that seems to be broken, and it has to be fixed. Could you perhaps write simple spec of what is not passing so we may then fix it ? Or if you have some experience with Scodec, this shall not be hard to fix.

**Comment by fommil** [comment] 2017-12-04 10:12
thanks @pchlupacek I should have added this to the original ticket. I'd expect the following to roundtrip

```
"http://x.com/123?a=1&b=2;c=3"

Uri(http,HostPort(x.com,None),Path(true,false,WrappedArray(123)),Query(List((a,1), (b,2;c=3))))
```

In an ideal world, the stringy map in `Query` would be an ADT that supports nested parameters and could therefore respond with something like

```
Query(List(Single(a,1), Multi(sep=";", List(Single(b,2), Single(c,3)))
```

with `Single` (what you currently support), `Multi` (with a custom separator... if this is `&` it should be encoded but `;` should not be encoded) and `Flag` for params with a key and no value.

**Comment by fommil** [comment] 2017-12-04 10:48
FYI I am using this workaround for generating the `String` version of the URL

```
import java.net.URLEncoder
import simulacrum._

@typeclass
trait UrlEncoded[A] { def urlEncoded(a: A): String }
object UrlEncoded {
  import ops._

  implicit val string: UrlEncoded[String] = { s =>
    URLEncoder
      .encode(s, "UTF-8")
      .replace("%2B", "+") // special-case flag parameters
      .replace("%3D", "=") // special-case nested parameters
      .replace("%3B", ";")
  }

  implicit val stringySeq: UrlEncoded[Seq[(String, String)]] = { m =>
    m.map {
      case (k, v) => s"${k.urlEncoded}=${v.urlEncoded}"
    }.mkString("&")
  }
}
```

with

```
  def stringify(u: Uri): String = {
    import UrlEncoded.ops._

    val scheme = u.scheme.toString
    val host   = u.host.host
    val port   = u.host.port.fold("")(p => s":$p")
    val path   = u.path.stringify
    val query  = u.query.params.toSeq.urlEncoded
    s"$scheme://$host$port$path?$query"
  }
```

it's a bit heavy-handed, but it meets my immediate requirements. I think basically a stringy map does not correctly capture what should/shouldn't be URL encoded in the query section.

**Comment by pchlupacek** [comment] 2017-12-05 12:40
Fixed in 0.3.0, fs2-http will follow shortly. Unfortunately 0.3.0 is not binary compatible with 0.2, so you may need to tweak a bit the user code.

**Closed as completed by pchlupacek** 2017-12-05 12:40 UTC

**Comment by fommil** [comment] 2017-12-05 13:58
This is really awesome, thank you! Technically any character (or escaped character) can be used to separate multipart queries (and they can be arbitrarily deep) but I think that's starting to get into super niche usage territory. The "rules" around what is and isn't URL encoded in such world in strange to me and I haven't quite figured it out.

**Comment by pchlupacek** [comment] 2017-12-05 14:34
yes, I have the same feeling. This does the job, we can always enhance for weird separators.
